version: "3"
services:
    backend:
        container_name: ws-simple-chat
        build:
            context: .
            dockerfile: Dockerfile
        image: mlazzarini/ws-simple-chat
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
    frontend:
        container_name: ws-simple-chat-app
        build:
            context: ./client
            dockerfile: Dockerfile
        image: mlazzarini/ws-simple-chat-app
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
        links:
            - backend
        stdin_open: true
